### ISSUE TITLE
Checkout form

### ISSUE THREAD

**Issue by anelson0828** [grace-shopper-1906/grace-shopper#8]
specify a shipping address and email address when I checkout, so that the items can arrive at the right place

**Comment by CoffeeJavaBeans** [comment]
Fields on checkout form
firstname lastname email address don't update the database just redux state 
component connected to user on state form should be able to change
update the database only for address field otherwise only redux state
address find or create
nothing should be null all fields required

if it is a guest do not worry about database just on react  state
